name: PR-Backup

on:
  pull_request:
    branches: [develop]
    types: [closed]
jobs:
  release:
    uses: migraphx-benchmark/actions/.github/workflows/backup.yml@main
    secrets:
      token: ${{ secrets.MIGRAPHX_BOT_TOKEN }}
