name: Backup test

on:
  workflow_dispatch:
env :
  PERFORMANCE_PATH: "/usr/share/migraphx/test-results"
  PERFORMANCE_DIR: performance-backup
  

jobs:
  backup:
    name: Backup_test_MM
    runs-on: self-hosted
    steps:
    - name: Checkout performance
      uses: actions/checkout@v3
      with:
       repository: migraphx-benchmark/performance-backup
       path: ${{ env.PERFORMANCE_DIR }}
       token: ${{ secrets.MIGRAPHX_BOT_TOKEN }}

    - name : run
      run: |
        echo "Checking dir"
        pwd && ls -la
        cd ${{ env.PERFORMANCE_PATH }}
        git add $(find . -type d -name "*perf*" -exec echo {} \;)
        git commit -m 'Added latest perf folders to backup'
        git status
        git push 
   