name: Backup test

on:
  workflow_dispatch:
env :
  PERFORMANCE_PATH: "/usr/share/migraphx/test-results"
  PERFORMANCE_DIR: performance-backup
  

jobs:
  backup:
    name: Backup_test_MM
    runs-on: self-hosted
    steps:
    - name: Checkout performance
      uses: actions/checkout@v3
      with:
       repository: migraphx-benchmark/performance-backup
       path: ${{ env.PERFORMANCE_DIR }}
       token: ${{ secrets.MIGRAPHX_BOT_TOKEN }}
    - name : run
      run: |
        echo "Check"
        cd ${{ env.PERFORMANCE_PATH }}
        git init
        # if ! git remote | grep -q '^origin$'; then
        git remote add origin https://github.com/migraphx-benchmark/performance-backup.git
        git branch -M main
        git config --local user.email github-actions
        git config --local user.name github-actions@github.com
        git add $(find . -type d -name "*perf*" -exec echo {} \;)
        git commit -m 'Added latest perf folders to backup'
        git status
        git push -u origin main
        # else
        #   git branch -M main
        #   git add $(find . -type d -name "*perf*" -exec echo {} \;)
        #   git commit -m 'testing purposes
        #   git push -u origin main'  
        # fi  

