name: MIGraphX Performance Tests HTEC dummy

on:

  #push:
  #  branches: [develop]

  pull_request:
    branches: [develop]
    types: [opened, synchronize, closed]

  schedule:
    - cron: "*/5 * * * *"

  workflow_dispatch:
    inputs:
      rocm_release:
        description: ROCm Version
        required: true
        default: '5.4.2'
      performance_reports_repo:
        description: Repository where performance reports are stored
        required: true
        default: "migraphx-benchmark/migraphx-reports"
      benchmark_utils_repo:
        description: Repository where benchmark utils are stored
        required: true
        default: "migraphx-benchmark/benchmark-utils"
      organization:
        description: Organization based on which location of files will be different
        required: true
        default: "HTEC"
#      migraphx_path:
#        description: Main migraphx directory
#        required: true
#        default: "/usr/share/migraphx/HTEC"
#      test_results_path:
#        description: Path to test results
#        required: true
#        default: "/usr/share/migraphx/HTEC/test-results"
#      reports_path:
#        description: Path to reports
#        required: true
#        default: "/usr/share/migraphx/HTEC/reports"
      result_number:
        description: Last N results
        required: true
        default: '10'
      flags:
        description: -m for Max value; -s for Std dev; -r for Threshold file
        required: true
        default: '-r'

concurrency: "perftest-${{ github.head_ref ||  github.base_ref || 'schedule' }}"

jobs:
  release:
    #if: ${{ github.event.label.name != 'skip bot checks' }}
    uses: migraphx-benchmark/actions/.github/workflows/perf-test-dummy.yml@main
    with:
      rocm_release: ${{ github.event.inputs.rocm_release || '5.4.2' }}
      result_number: ${{ github.event.inputs.result_number || '10' }}
      flags: ${{ github.event.inputs.flags || '-r' }}
      performance_reports_repo: ${{ github.event.inputs.performance_reports_repo || 'migraphx-benchmark/migraphx-reports' }}
      benchmark_utils_repo: ${{ github.event.inputs.benchmark_utils_repo || 'migraphx-benchmark/benchmark-utils' }}
      organization: ${{ github.event.inputs.organization || 'HTEC' }}
#      migraphx_path: ${{ github.event.inputs.migraphx_path || '/usr/share/migraphx/HTEC' }}
#      test_results_path: ${{ github.event.inputs.test_results_path || '/usr/share/migraphx/HTEC/test-results' }}
#      reports_path: ${{ github.event.inputs.reports_path || '/usr/share/migraphx/HTEC/reports' }}
    secrets:
      gh_token: ${{ secrets.MIGRAPHX_BOT_TOKEN }}
      mail_user: ${{ secrets.MAIL_USERNAME }}
      mail_pass: ${{ secrets.MAIL_PASSWORD }}
