name: ROCM Docker image build HTEC dj

on:
  workflow_dispatch:
    inputs:
      rocm_release:
        description: ROCm release version
        required: true
      benchmark-utils_repo:
        description: Repository for benchmark utils
        required: true
        default: 'migraphx-benchmark/benchmark-utils'
      overwrite:
        type: boolean
        description: Overwrite image if it already exists (true/false)
        required: true

jobs:
  release:
    uses: migraphx-benchmark/actions/.github/workflows/rocm-release-htec-dj.yml@main
    with:
      rocm_release: ${{ github.event.inputs.rocm_release }}
      benchmark-utils_repo: ${{ github.event.inputs.benchmark-utils_repo || 'migraphx-benchmark/benchmark-utils' }}
      overwrite: ${{ github.event.inputs.overwrite == 'true' }}
    secrets:
      gh_token: ${{ secrets.MIGRAPHX_BOT_TOKEN }}
